import type { Listing } from "./types";

export const demoListings: Listing[] = [
  { id: "demo-1", name: "Midnight Labs", tagline: "Ship less boring software.", url: "https://example.com/?brand=midnight", logo_url: null, bid_cents: 42000, clicks: 6184, active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "demo-2", name: "Sidequest", tagline: "Tiny tools for big procrastinators.", url: "https://example.com/?brand=sidequest", logo_url: null, bid_cents: 41900, clicks: 5579, active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "demo-3", name: "Okay Computer", tagline: "Automations that actually finish the job.", url: "https://example.com/?brand=okay", logo_url: null, bid_cents: 40100, clicks: 4932, active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "demo-4", name: "Human Error", tagline: "Bug reports with a pulse.", url: "https://example.com/?brand=human-error", logo_url: null, bid_cents: 37700, clicks: 4540, active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "demo-5", name: "Unicorn Rental", tagline: "Pretend your startup is profitable.", url: "https://example.com/?brand=unicorn", logo_url: null, bid_cents: 33300, clicks: 4088, active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "demo-6", name: "No Context", tagline: "Analytics without the weekly meeting.", url: "https://example.com/?brand=no-context", logo_url: null, bid_cents: 28500, clicks: 3291, active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "demo-7", name: "Ship It Friday", tagline: "Deploy irresponsibly, observe responsibly.", url: "https://example.com/?brand=ship-it", logo_url: null, bid_cents: 24600, clicks: 2864, active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "demo-8", name: "Overqualified", tagline: "Jobs for people tired of job boards.", url: "https://example.com/?brand=overqualified", logo_url: null, bid_cents: 20100, clicks: 2510, active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "demo-9", name: "Tabs Open", tagline: "Your browser deserves an intervention.", url: "https://example.com/?brand=tabs", logo_url: null, bid_cents: 17600, clicks: 1984, active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "demo-10", name: "Mild Panic", tagline: "Incident response for normal-sized disasters.", url: "https://example.com/?brand=panic", logo_url: null, bid_cents: 15100, clicks: 1771, active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "demo-11", name: "Reply All", tagline: "Email tools for people with enemies.", url: "https://example.com/?brand=reply-all", logo_url: null, bid_cents: 9900, clicks: 1321, active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "demo-12", name: "Zero Inbox", tagline: "A beautiful lie, now as a service.", url: "https://example.com/?brand=zero-inbox", logo_url: null, bid_cents: 5100, clicks: 841, active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }
];
